### ISSUE TITLE
Add snyk ignore for dsp repos via .snyk file

### ISSUE THREAD

**Issue by HumairAK** [red-hat-data-services/data-science-pipelines#51]
Currently there are a lot of folders/paths in dsp that we do not user (e.g. tekton-catalog, or front end), we should look into adding a .snyk file to ignore these errors for these paths.

**Comment by DharmitD** [comment]
PF [a demo](https://drive.google.com/file/d/1s8e7NJxU5SQQdQmaSJvL8y2JWg-laLGt/view?usp=sharing) that walks through this update.
